# Site settings
title: 'Welcome to my page' # Your Title
tagline: 'I use Ruby for web applications and make mobile clients with Android among other things...' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
highlighter: rouge
permalink: /:title
#baseurl: / # the subpath of your site, e.g. /blog/
twitter_username: eyewritecode
github_username:  eyewritecode