title: Uko Mbibona
description: My Personal blog
author: Thibault Mutabazi
github: https://github.com/eyewritecode
about: I know a thing or two about Ruby and NLP
disqus_shortname: eyewritecode
google_analytics: UA-128979628-1
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/eyewritecode"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/thibaultmutabazi"
    - icon: fa-github
      link: "https://github.com/eyewritecode"

share:
  twitter_username: eyewritecode

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://eyewritecode.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
