# Site settings
title: 'Call me Thibault' # Your Title
tagline: 'I use Ruby for web applications development and make mobile clients with Android' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
highlighter: rouge
permalink: /:title
#baseurl: / # the subpath of your site, e.g. /blog/
