# Site settings
title: Thibault Mutabazi
description: 'Hi there, I make web and mobile apps. What about you?'
baseurl: thibault.ml
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'eyewritecode'

author:
  name: 'Thibault Mutabazi'
  email: 933kss@gmail.com
  twitter_username: eyewritecode
  github_username:  eyewritecode
  instagram_username:  thibau.lt	
  linkedin_username:  thibaultmutabazi

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 4
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
